---

* name: Enterprise VM Monitoring
  hosts: all
  become: yes

  tasks:

  * name: CPU Usage
    shell: top -bn1 | grep "Cpu(s)"
    register: cpu

  * name: Memory Usage
    shell: free -h
    register: memory

  * name: Disk Usage
    shell: df -h
    register: disk

  * name: Uptime
    shell: uptime
    register: uptime

  * name: Running Services
    shell: systemctl list-units --type=service --state=running
    register: services

  * name: Report
    debug:
    msg:
    - "Host: {{ inventory_hostname }}"
    - "CPU: {{ cpu.stdout }}"
    - "Memory:"
    - "{{ memory.stdout }}"
    - "Disk:"
    - "{{ disk.stdout }}"
    - "Uptime:"
    - "{{ uptime.stdout }}"


